# Generated by Django 3.0.7 on 2020-07-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0002_auto_20200630_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcuser',
            name='useremail',
            field=models.EmailField(max_length=132, verbose_name='이메일'),
        ),
    ]
